name = "nuxthub-d1-repro"
compatibility_date = "2024-09-19"
compatibility_flags = ["nodejs_compat_v2"]
main = ".output/server/index.mjs"

[[d1_databases]]
binding = "DB"
database_name = "nuxthub-d1-repro"
database_id = "local"
